/**
 * Runtime port of the shipped ByteLevel BPE tokenizer (tokenizer.json —
 * fetched and parsed in the worker; Python and TypeScript consume identical
 * bytes, which is the parity story). Implements exactly what the HF
 * tokenizer does for this model: GPT-2 pre-tokenizer regex, byte-level
 * alphabet, rank-based BPE merges, the "[EOT]" added token, and a decode
 * whose DEFAULT skips special tokens (matching this tokenizers version —
 * that is how the training samples were decoded).
 *
 * Gated exactly by scripts/verify-storyteller-model.ts against fixtures
 * generated by training/storyteller/make_fixtures.py.
 */

const EOT_TOKEN = "[EOT]";

/** The GPT-2 pre-tokenizer pattern (HF ByteLevel use_regex split). */
const PRE_TOKENIZER =
  /'s|'t|'re|'ve|'m|'ll|'d| ?\p{L}+| ?\p{N}+| ?[^\s\p{L}\p{N}]+|\s+(?!\S)|\s+/gu;

/** bytes_to_unicode — GPT-2's 256-byte printable alphabet (Ġ = space, etc.). */
function buildByteAlphabet(): {
  encoder: string[];
  decoder: Map<string, number>;
} {
  const bs: number[] = [];
  for (let b = 33; b <= 126; b++) bs.push(b); // '!'..'~'
  for (let b = 161; b <= 172; b++) bs.push(b); // '¡'..'¬'
  for (let b = 174; b <= 255; b++) bs.push(b); // '®'..'ÿ'
  const cs = bs.slice();
  let n = 0;
  for (let b = 0; b < 256; b++) {
    if (!bs.includes(b)) {
      bs.push(b);
      cs.push(256 + n);
      n++;
    }
  }
  // bs and cs are parallel 256-entry lists — the encoder must be keyed BY BYTE
  // VALUE (bs[i] → cs[i]), not by list position, or every byte maps to the
  // wrong character (the classic bytes_to_unicode pitfall).
  const encoder = new Array<string>(256);
  const decoder = new Map<string, number>();
  bs.forEach((byte, i) => {
    const ch = String.fromCharCode(cs[i]);
    encoder[byte] = ch;
    decoder.set(ch, byte);
  });
  return { encoder, decoder };
}

const UTF8_ENCODER = new TextEncoder();

interface TokenizerJson {
  model: { vocab: Record<string, number>; merges: string[][] };
  added_tokens: { id: number; content: string; special: boolean }[];
}

export interface StorytellerTokenizer {
  readonly eotId: number;
  readonly vocabSize: number;
  encode(text: string): Uint16Array;
  decode(ids: ArrayLike<number>, skipSpecialTokens?: boolean): string;
  /** Raw UTF-8 bytes of one token's string form (the worker's streaming path). */
  tokenBytes(id: number): Uint8Array;
}

class ByteLevelBpe implements StorytellerTokenizer {
  readonly eotId: number;
  readonly vocabSize: number;
  private readonly vocab: Map<string, number>;
  private readonly idToToken: string[];
  private readonly ranks: Map<string, number>;
  private readonly byteEncoder: string[];
  private readonly byteDecoder: Map<string, number>;
  private readonly bpeCache = new Map<string, string[]>();

  constructor(json: TokenizerJson) {
    this.vocab = new Map(Object.entries(json.model.vocab));
    this.vocabSize = this.vocab.size;
    this.idToToken = new Array<string>(this.vocabSize);
    for (const [token, id] of this.vocab) this.idToToken[id] = token;
    this.ranks = new Map(
      json.model.merges.map(([a, b], i) => [`${a} ${b}`, i]),
    );
    const eot = json.added_tokens.find((t) => t.content === EOT_TOKEN);
    if (!eot || this.vocab.get(EOT_TOKEN) !== eot.id) {
      throw new Error(
        "The storyteller tokenizer file is missing its [EOT] token.",
      );
    }
    this.eotId = eot.id;
    const { encoder, decoder } = buildByteAlphabet();
    this.byteEncoder = encoder;
    this.byteDecoder = decoder;
  }

  private bpe(word: string[]): string[] {
    if (word.length < 2) return word;
    let parts = word;
    for (;;) {
      let bestRank = Infinity;
      let bestIdx = -1;
      for (let i = 0; i < parts.length - 1; i++) {
        const rank = this.ranks.get(parts[i] + " " + parts[i + 1]);
        if (rank !== undefined && rank < bestRank) {
          bestRank = rank;
          bestIdx = i;
        }
      }
      if (bestIdx === -1) return parts;
      parts = parts
        .slice(0, bestIdx)
        .concat(parts[bestIdx] + parts[bestIdx + 1], parts.slice(bestIdx + 2));
    }
  }

  private bpeCached(preToken: string): string[] {
    const cached = this.bpeCache.get(preToken);
    if (cached) return cached;
    // Map the pre-token's UTF-8 bytes through the printable alphabet, then merge.
    const bytes = UTF8_ENCODER.encode(preToken);
    const chars = new Array<string>(bytes.length);
    for (let i = 0; i < bytes.length; i++)
      chars[i] = this.byteEncoder[bytes[i]];
    const merged = this.bpe(chars);
    this.bpeCache.set(preToken, merged);
    return merged;
  }

  encode(text: string): Uint16Array {
    const ids: number[] = [];
    // Added-token semantics: split on the [EOT] literal first (id inserted as-is).
    const segments = text.split(EOT_TOKEN);
    for (let s = 0; s < segments.length; s++) {
      for (const piece of segments[s].match(PRE_TOKENIZER) ?? []) {
        for (const token of this.bpeCached(piece)) {
          const id = this.vocab.get(token);
          if (id === undefined) {
            throw new Error(
              "The storyteller tokenizer can't encode this text — the tokenizer file may be corrupted.",
            );
          }
          ids.push(id);
        }
      }
      if (s < segments.length - 1) ids.push(this.eotId);
    }
    return Uint16Array.from(ids);
  }

  tokenBytes(id: number): Uint8Array {
    if (id === this.eotId) return UTF8_ENCODER.encode(EOT_TOKEN);
    const token = this.idToToken[id];
    if (token === undefined) {
      throw new Error(
        "The storyteller tokenizer was asked for a token id that doesn't exist.",
      );
    }
    const out = new Uint8Array(token.length);
    for (let i = 0; i < token.length; i++) {
      out[i] = this.byteDecoder.get(token[i]) ?? 0;
    }
    return out;
  }

  decode(ids: ArrayLike<number>, skipSpecialTokens = true): string {
    const bytes: number[] = [];
    for (let i = 0; i < ids.length; i++) {
      const id = ids[i];
      if (id === this.eotId) {
        if (!skipSpecialTokens) {
          for (const b of UTF8_ENCODER.encode(EOT_TOKEN)) bytes.push(b);
        }
        continue;
      }
      const token = this.idToToken[id];
      if (token === undefined) {
        throw new Error(
          "The storyteller tokenizer was asked to decode a token id that doesn't exist.",
        );
      }
      for (let j = 0; j < token.length; j++) {
        bytes.push(this.byteDecoder.get(token[j]) ?? 0);
      }
    }
    return new TextDecoder().decode(Uint8Array.from(bytes));
  }
}

export function buildTokenizer(jsonText: string): StorytellerTokenizer {
  return new ByteLevelBpe(JSON.parse(jsonText) as TokenizerJson);
}

/** Incremental decoder for streaming generation (handles multibyte splits). */
export class StreamingStorytellerDecoder {
  private readonly decoder = new TextDecoder();

  constructor(
    private readonly tokenizer: StorytellerTokenizer,
    private readonly skipSpecialTokens = true,
  ) {}

  push(id: number): string {
    if (id === this.tokenizer.eotId) {
      return this.skipSpecialTokens ? "" : EOT_TOKEN;
    }
    return this.decoder.decode(this.tokenizer.tokenBytes(id), { stream: true });
  }
}
