"""Export the llm-from-scratch pc-tiny checkpoint into the portfolio's "STOR" container.

Reads the sibling repo's checkpoint IN PLACE (never copied, never committed),
asserts the tied head shares storage (and writes it once), quantizes fp16
(round-to-nearest-even — the TS decode is exact), and writes:

  public/models/storyteller/storyteller.bin    32-B STOR v1 header + fp16 payload
  public/models/storyteller/tokenizer.json     byte-identical copy
  lib/storyteller/trainingData.ts               generated from training_log.json

Then self-checks: re-reads the container, dequantizes, and proves last-position
logits (tolerance) and a greedy continuation match the fp32 master.

Run on James's machine — never on Vercel. The Python deps (torch, numpy,
tokenizers) live in the llm-from-scratch venv:

  C:/Users/User/Documents/Repositories/dev/llm-from-scratch/.venv/Scripts/python.exe \\
    training/storyteller/export.py [--ckpt <path>]
"""

from __future__ import annotations

import argparse
import hashlib
import json
import struct
import sys
import zlib
from pathlib import Path

import numpy as np
import torch

ROOT = Path(__file__).resolve().parents[2]  # portfolio root
TRAINING = ROOT / "training" / "storyteller"
PUBLIC_MODELS = ROOT / "public" / "models" / "storyteller"
LIB_STORYTELLER = ROOT / "lib" / "storyteller"

MAGIC = b"STOR"
VERSION = 1
DTYPE_FP16 = 1
FLAG_TIED_HEAD = 0b01
FLAG_ROPE_INTERLEAVED = 0b10

EXPECTED_CONFIG = {"n_layer": 6, "n_embd": 256, "n_head": 8, "ctx_len": 256, "vocab_size": 8192}
EXPECTED_PARAMS = 6_917_376
EXPECTED_PAYLOAD = 13_834_752

# The payload order — the single layout contract shared by export.py,
# reference.py, and lib/storyteller/container.ts.
PAYLOAD_ORDER = (
    ["wte.weight"]
    + [
        f"h.{i}.{part}"
        for i in range(EXPECTED_CONFIG["n_layer"])
        for part in (
            "ln1.weight",
            "attn.qkv.weight",
            "attn.proj.weight",
            "ln2.weight",
            "ffn.w1.weight",
            "ffn.w3.weight",
            "ffn.w2.weight",
        )
    ]
    + ["norm_f.weight"]
)


def parse_args() -> argparse.Namespace:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument(
        "--ckpt",
        type=Path,
        default=ROOT.parent / "llm-from-scratch" / "ckpts" / "latest.pt",
    )
    return ap.parse_args()


def pack_container(cfg: dict, tensors: list[torch.Tensor]) -> tuple[bytes, dict]:
    payload = b"".join(t.detach().cpu().contiguous().numpy().astype(np.float16).tobytes() for t in tensors)
    assert len(payload) == EXPECTED_PAYLOAD, f"payload {len(payload):,} != {EXPECTED_PAYLOAD:,}"
    crc = zlib.crc32(payload) & 0xFFFFFFFF
    header = struct.pack(
        "<4sHBBHBBHHIIII",
        MAGIC,
        VERSION,
        DTYPE_FP16,
        FLAG_TIED_HEAD | FLAG_ROPE_INTERLEAVED,
        cfg["n_embd"],
        cfg["n_layer"],
        cfg["n_head"],
        cfg["ctx_len"],
        cfg["vocab_size"],
        EXPECTED_PARAMS,
        crc,
        len(payload),
        0,
    )
    assert len(header) == 32
    facts = {
        "crc32": crc,
        "payloadBytes": len(payload),
        "paramCount": EXPECTED_PARAMS,
    }
    return header + payload, facts


def write_training_data() -> None:
    log = json.loads((TRAINING / "training_log.json").read_text(encoding="utf-8"))
    evals, samples = log["evals"], log["samples"]
    assert len(evals) == 41 and len(samples) == 16, (len(evals), len(samples))
    LIB_STORYTELLER.mkdir(exist_ok=True)
    body = "\n".join(
        [
            "// GENERATED by training/storyteller/export.py from training_log.json — do not edit.",
            "// Values are the measured 2026-09-22 pc-tiny run: 4,000 steps, ~100 min CPU.",
            "",
            "export interface LossPoint {",
            "  step: number;",
            "  valLoss: number;",
            "}",
            "",
            "export interface EvolutionSample {",
            "  step: number;",
            "  text: string;",
            "}",
            "",
            "export const LOSS_POINTS: readonly LossPoint[] = ",
            json.dumps(evals, indent=2) + ";",
            "",
            "export const EVOLUTION_SAMPLES: readonly EvolutionSample[] = ",
            json.dumps(samples, indent=2) + ";",
            "",
            "export const TRAINING_FACTS = {",
            "  params: 6_917_376,",
            "  corpusTokens: 66_674_390,",
            "  valTokens: 382_823,",
            "  steps: 4_000,",
            "  startValLoss: " + f"{evals[0]['valLoss']},",
            "  finalValLoss: " + f"{evals[-1]['valLoss']},",
            "  finalValPpl: 7.4,",
            "  trainingMinutes: 100,",
            "} as const;",
            "",
        ]
    )
    out = LIB_STORYTELLER / "trainingData.ts"
    out.write_text(body, encoding="utf-8", newline="\n")
    print(f"wrote {out} ({out.stat().st_size:,} B)")


def dequantize(container: Path) -> dict[str, np.ndarray]:
    """Re-read the container and map payload positions back to state-dict keys."""
    raw = container.read_bytes()
    magic, version, dtype, flags, n_embd, n_layer, n_head, ctx_len, vocab, pc, crc, nbytes, _ = struct.unpack("<4sHBBHBBHHIIII", raw[:32])
    assert magic == MAGIC and version == VERSION and dtype == DTYPE_FP16, (magic, version, dtype)
    assert (zlib.crc32(raw[32:32 + nbytes]) & 0xFFFFFFFF) == crc, "crc mismatch on re-read"
    f32 = np.frombuffer(raw[32:32 + nbytes], dtype="<f2").astype(np.float32)
    assert f32.size == EXPECTED_PARAMS

    d, hidden = n_embd, ((int(n_embd * 8 / 3) + 63) // 64) * 64
    shapes = {"wte.weight": (vocab, d), "norm_f.weight": (d,)}
    for i in range(n_layer):
        shapes[f"h.{i}.ln1.weight"] = (d,)
        shapes[f"h.{i}.attn.qkv.weight"] = (3 * d, d)
        shapes[f"h.{i}.attn.proj.weight"] = (d, d)
        shapes[f"h.{i}.ln2.weight"] = (d,)
        shapes[f"h.{i}.ffn.w1.weight"] = (hidden, d)
        shapes[f"h.{i}.ffn.w3.weight"] = (hidden, d)
        shapes[f"h.{i}.ffn.w2.weight"] = (d, hidden)

    out, pos = {}, 0
    for key in PAYLOAD_ORDER:
        n = int(np.prod(shapes[key]))
        out[key] = f32[pos : pos + n].reshape(shapes[key])
        pos += n
    assert pos == EXPECTED_PARAMS
    out["lm_head.weight"] = out["wte.weight"]  # tied
    return out


def greedy(model, ids: torch.Tensor, n: int) -> list[int]:
    for _ in range(n):
        with torch.no_grad():
            logits, _ = model(ids[:, -model.cfg.ctx_len :])
        ids = torch.cat([ids, torch.tensor([[int(logits[0].argmax())]])], dim=1)
    return ids[0].tolist()


def self_check(container: Path, ckpt: Path, cfg: dict) -> None:
    repo = ckpt.parents[1]
    sys.path.insert(0, str(repo))
    from config import ModelConfig  # noqa: E402  (llm-from-scratch repo)
    from model import GPT  # noqa: E402
    from tokenizers import Tokenizer  # noqa: E402

    mcfg = ModelConfig(**{k: cfg[k] for k in ("n_layer", "n_embd", "n_head", "ctx_len", "vocab_size")})

    original = GPT(mcfg)
    original.load_state_dict(torch.load(ckpt, map_location="cpu", weights_only=False)["model"])
    original.eval()

    deq_sd = {k: torch.from_numpy(v.copy()) for k, v in dequantize(container).items()}
    dequantized = GPT(mcfg)
    dequantized.load_state_dict(deq_sd)
    dequantized.eval()

    tok = Tokenizer.from_file(str(repo / "tokenizer" / "tokenizer.json"))
    for prompt in ("Once upon a time", "Lily and the little bird", "The cat sat on the"):
        ids = torch.tensor([tok.encode(prompt).ids], dtype=torch.long)
        with torch.no_grad():
            l_orig, _ = original(ids)
            l_deq, _ = dequantized(ids)
        diff = (l_orig - l_deq).abs().max().item()
        assert diff < 5e-2, f"fp16 logit drift too large for {prompt!r}: {diff}"
        g_orig = greedy(original, ids.clone(), 8)
        g_deq = greedy(dequantized, ids.clone(), 8)
        assert g_orig == g_deq, f"greedy paths diverged for {prompt!r}: {g_orig} != {g_deq}"
        print(f"  self-check ok: {prompt!r} maxLogitDiff {diff:.4g}, greedy match")


def main() -> None:
    args = parse_args()
    state = torch.load(args.ckpt, map_location="cpu", weights_only=False)
    cfg, preset = state["config"], state["preset"]
    assert preset == "pc-tiny", f"unexpected preset {preset!r}"
    assert cfg == EXPECTED_CONFIG, f"unexpected config {cfg}"

    sd = state["model"]
    wte, head = sd["wte.weight"], sd["lm_head.weight"]
    assert wte.data_ptr() == head.data_ptr() and wte.shape == head.shape, (
        "wte and lm_head must be the tied tensor (shared storage)"
    )
    del head  # the tie is proven; the payload writes wte exactly once

    tensors = [sd[key] for key in PAYLOAD_ORDER]
    params = sum(t.numel() for t in tensors)
    assert params == EXPECTED_PARAMS, f"param count {params:,} != {EXPECTED_PARAMS:,}"

    blob, facts = pack_container(cfg, tensors)
    PUBLIC_MODELS.mkdir(parents=True, exist_ok=True)
    bin_out = PUBLIC_MODELS / "storyteller.bin"
    bin_out.write_bytes(blob)
    digest = hashlib.sha256(blob).hexdigest()
    print(f"wrote {bin_out} ({bin_out.stat().st_size:,} B) sha256 {digest[:16]}… crc32 {facts['crc32']:08x}")

    tok_src = args.ckpt.parents[1] / "tokenizer" / "tokenizer.json"
    tok_bytes = tok_src.read_bytes()
    tok_out = PUBLIC_MODELS / "tokenizer.json"
    tok_out.write_bytes(tok_bytes)
    assert tok_out.read_bytes() == tok_bytes
    print(f"wrote {tok_out} ({tok_out.stat().st_size:,} B, byte-identical to {tok_src.name})")

    write_training_data()

    print("self-check (fp16 container vs fp32 master):")
    self_check(bin_out, args.ckpt, cfg)
    print("export complete — run make_fixtures.py next")


if __name__ == "__main__":
    main()