"""Generate the golden fixtures for the storyteller parity gate.

Everything here derives from the SHIPPED artifacts — the fp16 STOR container
and the byte-identical tokenizer copy — never from an fp32 master, so the
TypeScript port is gated against the exact bytes the browser loads.

Outputs training/storyteller/fixtures/storyteller_fixtures.json (committed).
Run on James's machine — never on Vercel (same venv as export.py).
"""

from __future__ import annotations

import hashlib
import json
import struct
from pathlib import Path

import numpy as np
from tokenizers import Tokenizer

import reference

ROOT = Path(__file__).resolve().parents[2]
TRAINING = ROOT / "training" / "storyteller"
BIN = ROOT / "public" / "models" / "storyteller" / "storyteller.bin"
TOK = ROOT / "public" / "models" / "storyteller" / "tokenizer.json"

TOKENIZER_CASES = [
    "Once upon a time",
    "Lily and the little bird",
    "She couldn't stop—it's Timmy's ball.",
    "a  b\tc\n\nd",
    "The cat sat on the",
    "小猫在花园里玩。",
    "A 🐱 and a 🐶 played 😊.",
    "x[EOT]y",
    "",
    "a b",
]

FORWARD_PROMPTS = [
    "Once upon a time",
    "Lily and the little bird",
    "The cat sat on the",
]


def sig5(x: float) -> float:
    """Round to 5 significant digits — the fixture storage convention."""
    return float(f"{float(x):.5g}")


def main() -> None:
    assert BIN.exists(), "run export.py first"
    raw = BIN.read_bytes()
    tok = Tokenizer.from_file(str(TOK))

    cfg, weights, header = reference.load_container(BIN)
    assert header["paramCount"] == 6_917_376

    # --- tokenizer exact cases -------------------------------------------
    # This tokenizers version's DEFAULT decode skips special tokens ([EOT] is
    # dropped) — that is how sample.py decoded the real generations, so the TS
    # port must mirror BOTH decode modes. The no-skip decode must round-trip
    # every text (including the literal "[EOT]").
    tokenizer_cases = []
    for text in TOKENIZER_CASES:
        ids = tok.encode(text).ids
        assert tok.decode(ids, skip_special_tokens=False) == text, (
            f"decode(encode({text!r})) mismatch"
        )
        tokenizer_cases.append({"text": text, "ids": ids, "decodeDefault": tok.decode(ids)})

    decode_cases = []
    for text in ("Once upon a time", "x[EOT]y", "A 🐱 and a 🐶 played 😊."):
        ids = tok.encode(text).ids
        decode_cases.append(
            {
                "ids": ids,
                "textDefault": tok.decode(ids),
                "textNoSkip": tok.decode(ids, skip_special_tokens=False),
            }
        )
    decode_cases.append(
        {
            "ids": [0],
            "textDefault": tok.decode([0]),
            "textNoSkip": tok.decode([0], skip_special_tokens=False),
        }
    )

    # --- container facts + fp16 spots ------------------------------------
    payload = raw[32:]
    fp16 = np.frombuffer(payload, dtype="<u2")
    spots = [0, 1, 999_999, 2_097_152, 4_000_000, 6_917_375]
    fp16_spots = [
        {"index": i, "bits": int(fp16[i]), "value": float(np.frombuffer(fp16[i : i + 1].tobytes(), dtype="<f2")[0])}
        for i in spots
    ]

    # --- rope --------------------------------------------------------------
    inv_freq = 1.0 / (reference.ROPE_BASE ** (np.arange(0, cfg.head_dim, 2, dtype=np.float64) / cfg.head_dim))
    cos_full, sin_full = reference.rope_tables(cfg.head_dim, cfg.ctx_len)
    rope = {
        "invFreq": [sig5(v) for v in inv_freq],
        "cos8x16": [sig5(v) for v in cos_full[:8].reshape(-1)],
        "sin8x16": [sig5(v) for v in sin_full[:8].reshape(-1)],
    }

    # --- forward parity cases ----------------------------------------------
    forward_cases = []
    for prompt in FORWARD_PROMPTS:
        ids = tok.encode(prompt).ids
        assert 1 <= len(ids) <= cfg.ctx_len
        logits = reference.forward_last_logits(cfg, weights, ids)
        order = np.argsort(-logits)  # stable enough for top-32; argmax breaks ties by first index
        forward_cases.append(
            {
                "prompt": prompt,
                "ids": ids,
                "logitsFirst64": [sig5(v) for v in logits[:64]],
                "logitsTop32": [{"id": int(i), "value": sig5(logits[i])} for i in order[:32]],
                "argmaxId": int(np.argmax(logits)),
                "greedyIds": reference.greedy_continuation(cfg, weights, ids, 4)[len(ids) :],
            }
        )

    fixtures = {
        "note": (
            "Generated by training/storyteller/make_fixtures.py from the SHIPPED "
            "fp16 container + tokenizer (never an fp32 master). Tolerances: "
            "abs 1e-5 OR rel 1e-3 on 5-significant-digit values; ids and fp16 spots exact."
        ),
        "config": {
            "n_layer": cfg.n_layer, "n_embd": cfg.n_embd, "n_head": cfg.n_head,
            "ctx_len": cfg.ctx_len, "vocab_size": cfg.vocab_size,
            "hidden": cfg.hidden, "head_dim": cfg.head_dim,
        },
        "paramCount": 6_917_376,
        "container": {
            "sha256": hashlib.sha256(raw).hexdigest(),
            "binBytes": len(raw),
            "tokenizerBytes": TOK.stat().st_size,
            "header": header,
        },
        "tokenizerCases": tokenizer_cases,
        "decodeCases": decode_cases,
        "fp16Spots": fp16_spots,
        "rope": rope,
        "forwardCases": forward_cases,
    }

    out = TRAINING / "fixtures" / "storyteller_fixtures.json"
    out.write_text(json.dumps(fixtures, indent=2) + "\n", encoding="utf-8")
    n_eot = any(0 in c["ids"] for c in tokenizer_cases)
    print(f"wrote {out} ({out.stat().st_size:,} B)")
    print(f"  tokenizer cases: {len(tokenizer_cases)} (EOT literal covered: {n_eot})")
    print(f"  forward cases: {len(forward_cases)} — greedy tails { [c['greedyIds'] for c in forward_cases] }")
    print(f"  container sha256 {fixtures['container']['sha256'][:16]}…")


if __name__ == "__main__":
    main()