/**
 * GENERATED by training/llm/make_corpora.py — do not hand-edit.
 * James's approved site copy: content/jtb/{about, ai, career, education, experience, ml, projects, skills}.md
 * with markdown syntax and [TODO placeholder lines stripped (the same
 * text JTB is grounded in). Tiny by design — models memorise it.
 * sha256 4c382b098cec4f2f...
 */

export const PORTFOLIO_CORPUS = `Overview
James Imbuido is a Data Scientist and AI Engineer based in Victoria, Australia. He builds in Python and R, and is currently an Associate Data Scientist at Commonwealth Bank of Australia (CBA).
Current role
James is currently an Associate Data Scientist at CBA, applying Agentic AI Engineering across the bank to take a proof-of-concept AI solution into production.
Background
Before data science, James worked for four years as a Registered Nurse in Victorian hospitals — most recently as a mental-health case manager in Maroondah, and earlier through pediatric oncology and ICU rotations at Dandenong Hospital, where he learned to synthesise clinical data across teams and act on it under pressure.
James holds an MSc Data Science (Distinction) and a Bachelor of Nursing (Distinction).
How he thinks about technology
James is fascinated with the human mind, which is why he has a background in nursing (specialising in psychology and mental health). He combined that with an interest in technology to pursue the study of Machine Learning and Artificial Intelligence — the closest comparison he knows to how the human mind works.
Technology, to James, is only as good as the people it serves. His years in nursing taught him that the best tools are the ones that let a team act with confidence under pressure, and that a number, model, or dashboard is worthless if it cannot be trusted or acted on. He cares less about cleverness for its own sake and more about whether what he builds helps someone make a better decision.
Where to find him online
James can be reached via the Contact page on this site, which lists his email, LinkedIn, GitHub, and Kaggle profiles:
Email: jtb9029@protonmail.com
LinkedIn: https://www.linkedin.com/in/jamesimbuido/
GitHub: https://github.com/jimbuido08
Kaggle: https://www.kaggle.com/jamesimbuido

GenFolio (CBA, AI-Powered Engineering)
James architected a generative-AI and agentic solution and scaled it from proof-of-concept into a deployed production web application used by ~1,000+ internal engineers — built on AWS, Vercel AI, and Anthropic's Claude foundation models. He was the Data Science & AI lead for this work, key developer and data scientist productionising GenFolio, and deployed the MVP to production within 3 months of starting development.
Agentic AI at CBA
James is currently an Associate Data Scientist applying Agentic AI Engineering across CBA to take a proof-of-concept AI solution into production. In an earlier rotation he integrated agentic GenAI frameworks and agents into a Retrieval-Augmented Generation (RAG) and LLM codebase infrastructure.
AI evaluation
James ran generative-AI and agentic evaluations of AI solutions in production, improving evaluation scores by ~20% using LLM-as-a-judge and a fully automated, self-improving pipeline on GitHub Actions with HoneyHive.
AI education and community
James initiated and delivered CBA's Claude Code beginner workshops — 2,000+ participants across Melbourne (372), Sydney (1,000), and Perth (650) — running the Melbourne sessions independently. He also presented CBA's AIPE-in-Action event on advanced Claude Code topics, facilitated CBA's internal Data Science Graduate Learning Lab, mentored high-school students through ABCN, and presented keynotes to teams on AI, Data & Analytics, and agentic AI agents.

Career path
James's career moved from clinical nursing into data science and AI engineering.
Worked for four years as a Registered Nurse in Victorian hospitals — most recently as a mental-health case manager in Maroondah, and earlier through pediatric oncology and ICU rotations at Dandenong Hospital — where he learned to synthesise clinical data across teams and act on it under pressure.
Combined a nursing background (specialising in psychology and mental health) with an interest in technology to pursue Machine Learning and Artificial Intelligence — completing an MSc in Data Science (Distinction) at James Cook University.
Joined Commonwealth Bank of Australia (CBA) in Feb 2025 as a Graduate Data Scientist, rotating through General Audit & Assurance and AI-Powered Engineering, and winning Hackathon25 with the GenFolio team.
Now an Associate Data Scientist at CBA (Feb 2026 — Present), applying Agentic AI Engineering across the bank to take a proof-of-concept AI solution into production.

Master of Data Science — James Cook University (Jan 2023 — Aug 2024)
A two-year full-time accredited degree in data science and computer science, completed in 1 year 8 months and awarded with Distinction. Focus areas include Generative AI and Artificial Intelligence.
Bachelor of Nursing — Monash University (Mar 2020 — Dec 2022)
A three-year full-time AHPRA-certified degree, awarded with Distinction.
Victorian Certificate of Education — Emmaus College (2014 — 2019)
High school diploma — awarded with a 92.95 ATAR.
Activities & societies: Tennis Team Inter-School Sport Captain, Table Tennis Team Inter-School Sport Captain, Badminton Inter-School Sport Player (ranked 4th), Soccer Inter-School Sport Player, Athletics Inter-School Sport Athlete (field and track), Art Committee Member, Musical Production Cast Member (Hairspray), Vinnies Victoria Committee Member, and Junior High Representative.
Licenses & certifications
**Anthropic (Jul 2026):**
AI Fluency for Builders
AI Fluency for Small Businesses
AI Capabilities and Limitations
Introduction to Subagents
Introduction to Agent Skills
Model Context Protocol: Advanced Topics
Introduction to Claude Cowork
Claude Platform 101
Claude Code 101
**Anthropic (Mar 2026):**
Claude with Claude API (ID: mkzibddwfgbs)
Claude with Amazon Bedrock (ID: 3y469k5qyhry)
Introduction to Model Context Protocol (MCP) (ID: qt23vjduvmka)
AI Fluency for nonprofits
AI Fluency for Educators
Teaching AI Fluency
AI Fluency for students
AI Fluency: Framework & Foundations
Claude 101
Claude Code in Action (ID: ij7ga7ywdbs7)
**Udemy (Jul 2026):**
SOLID Principles of Object Oriented Design and Architecture (ID: UC-c6b6f87a-fbff-416b-84c0-e49a8173da8b)
Software Architecture & Design of Modern Large Scale Systems (ID: UC-27fa67c8-b731-486e-9f0a-39d642409617)
**Udemy (Jun 2026):**
Mathematics — Basics to Advanced for Data Science and GenAI (ID: UC-ce0ca1d8-97ef-42be-afe9-3df1c63adfa7)
**Udemy (Mar 2025):**
Master Git and GitHub in 5 Days: Go from Zero to Hero (ID: UC-694830f8-b0d1-46a9-b4c2-43025bbc6ae7)
The Complete SQL Bootcamp: Go from Zero to Hero (ID: UC-1e590e1f-e8f1-492d-b339-6744ee28968c)
**Coursera (Mar 2022):**
Google Data Analytics Specialization (ID: YCDDYN3GNSPY)
**Udemy (Mar 2022):**
Python for Data Science and Machine Learning Bootcamp (ID: UC-f4581ad4-7c98-41b0-aeb4-82655a7deaab)
The Data Science Course 2022: Complete Data Science Bootcamp (ID: UC-fb1749be-c7b2-472d-9d72-c2738f06e0df)
**freeCodeCamp (Jan 2022):**
Data Visualization
Front End Development Libraries
**freeCodeCamp (Dec 2021):**
JavaScript Algorithms and Data Structures
**freeCodeCamp (Nov 2021):**
Responsive Web Design Developer Certification
**LinkedIn Learning (Dec 2021):**
Become a Software Developer
Programming Foundations: Web Security
Learning SQL Programming
Learning C#
Learning Java
JavaScript Essential Training
Learning Python (2020)
CSS Essential Training
HTML Essential Training
Succeeding in Web Development: Full Stack and Front End
Programming Foundations: Databases
Programming Foundations: Fundamentals
**Udemy (Nov 2021):**
Microsoft Excel — Excel from Beginner to Advanced (ID: UC-cb3272a3-4bf9-4b4f-80ed-7cc90371f9dd)
**Udemy (Sep 2021):**
2021 Complete Python Bootcamp From Zero to Hero in Python (ID: UC-c26e26df-2a9c-4df7-88aa-3f76e17735f3)

Associate Data Scientist — Commonwealth Bank of Australia (Feb 2026 — Present)
Full-time, hybrid, based in Melbourne, Victoria. James is currently in CBA's AI-Capabilities · SuperVerse placement.
AI-Capabilities · SuperVerse:
Implemented SQL queries to ensure the automated modeling software directs to the relevant data tables. Involved technologies include SQL, Snowflake, GDW, and Teradata.
Previously within this role, as part of AI-Powered Engineering (AIPE) · GenFolio:
As Data Science & AI lead, architected a generative-AI and agentic solution and scaled it from proof-of-concept into a deployed production web application used by ~1,000+ internal engineers — built on AWS, Vercel AI, and Anthropic's Claude foundation models.
Ran generative-AI and agentic evaluations of AI solutions in production, improving evaluation scores by ~20% using LLM-as-a-judge and a fully automated, self-improving pipeline on GitHub Actions with HoneyHive.
The manual documentation and preparation for periodic managerial conversations and performance reviews were addressed by the Generative AI solution (GenFolio), streamlining this process from weeks to a few hours.
AI Adoption & Community Engagement:
Initiated and delivered CBA's Claude Code beginner workshops — 2,000+ participants across Melbourne (372), Sydney (1,000), and Perth (650) — running the Melbourne sessions independently.
Presented CBA's AIPE-in-Action event, delivering a workshop on advanced Claude Code topics and techniques.
Facilitated and presented at CBA's internal Data Science Graduate Learning Lab.
Mentored high-school students through ABCN programs, and networked with tech talent across the University of Melbourne, CBA, and Swinburne University.
Graduate Data Scientist — Commonwealth Bank of Australia (Feb 2025 — Feb 2026)
Full-time, Australia.
**Rotation 2 · AI-Powered Engineering (AIPE) Management · GenFolio:** Key developer and data scientist productionising GenFolio for the Engineering Practice — deployed an MVP to production within 3 months of starting development. Ran multiple pilot groups for continuous product testing and improvement. Provided data-science support to AIPE and panelled and mentored for NSW VET.
**Hackathon25! · Collabor(A.I.)te & Innovate · GenFolio:** Competed in a company-wide hackathon against 260+ CBA teams across Australia and India — placed 1st in the group's first-ever company-wide hackathon. Deliberated on scaling and productionising the product, gaining exclusive executive sponsorship from the group's Chief Information Officer (CIO) for Technology.
**Rotation 1 · General Audit & Assurance (GA&A):** Integrated agentic GenAI frameworks and agents into a Retrieval-Augmented Generation (RAG) and LLM codebase infrastructure. Presented and facilitated keynotes to the wider team on AI, Data & Analytics, and agentic AI agents. Completed ad-hoc data-science support for audit groups, and facilitated a 2-week immersive sprint with auditors on getting the most from an automated audit pipeline — covering AI, agents, and LLM governance and model risk.
**Graduate Modelling Project · Consumer Finance:** Evaluated an initial machine-learning model for suspected bias, rectified the discovered biases in the second iteration, and presented the outcomes to stakeholders covering both technical and business aspects.
Registered Nurse and Case Manager — Eastern Health (Jan 2023 — Feb 2025)
Full-time, Maroondah, Victoria. Provided evidence-based mental-health nursing care for residents and clients, working from care plans developed collaboratively with the client, their medical officer, and the wider care team — including case management of short- and long-term clients to support optimal rehabilitation.
Registered Undergraduate Student Nurse (RUSON) — Eastern Health (Oct 2021 — Dec 2022)
Part-time, Victoria. Supported the nursing team in delivering safe, effective care across vaccination clinics, the emergency department, and the renal unit — through both administrative and clinical tasks.
Support Worker — Compassion Care Network (Jul 2021 — Dec 2022)
Part-time. Supported people with disabilities in their homes to promote independent living — assisting with activities of daily living, coordinating care plans with other healthcare providers, and facilitating social activities.
Nursing Student — Monash Health (Feb 2022 — May 2022)
Internship at Dandenong Hospital. Provided evidence-based nursing care working from collaborative care plans; carried full patient loads — 4 patients in Paediatric Oncology and 1–2 in ICU, including patients with ventilators, tracheostomies, drains, PCAs, CVCs, PICCs, ART lines, and COVID-19 risk.
Earlier roles
**Nursing Student — Ramsay Health Care** (Jan 2022 — Feb 2022, Mitcham, VIC): mental-health nursing care from collaborative care plans.
**Nursing Student — Peninsula Health** (Jan 2022, Frankston, VIC): general-surgery nursing care from collaborative care plans.
**Nursing Student — Kingston Rehabilitation & Nursing Center** (Jun 2021 — Jul 2021, Melbourne, VIC): rehabilitation nursing care from collaborative care plans.
**Admissions Officer — Box Hill Institute** (Jan 2021 — Feb 2021, VIC): evaluated applications and made admissions decisions — reviewing transcripts, test scores, references, and personal statements; conducted interviews and made recommendations to the Admissions Committee.
**Call Center & Customer Experience Representative — Box Hill Institute** (Nov 2020 — Dec 2020, VIC): answered customer questions, resolved issues, and provided a positive customer experience.
**Nursing Student — Peter James Center** (Jun 2020 — Jul 2020, Melbourne, VIC): aged-care nursing care from collaborative care plans.
**Retail Sales Associate — MYER** (2017, Knoxfield, VIC).

Graduate Modelling Project — Consumer Finance (CBA)
As part of CBA's graduate program, James evaluated an initial machine-learning model for suspected bias, rectified the discovered biases in the second iteration of the model, and presented the outcomes to stakeholders covering both technical and business aspects.
Production evaluation of AI solutions (CBA)
James ran generative-AI and agentic evaluations of AI solutions in production, improving evaluation scores by ~20% using LLM-as-a-judge and a fully automated, self-improving pipeline on GitHub Actions with HoneyHive.
ML tooling James uses
Python and R, with NumPy, Pandas, and PySpark; applied mathematics and data analysis for modelling work.

JTB — James Talks Back (this site)
JTB is the chatbot visitors are talking to right now — a RAG (Retrieval-Augmented Generation) application James built for this portfolio. It answers questions grounded exclusively in a curated knowledge base of approved markdown about him, using pgvector-based retrieval with a whole-KB fallback, so it is designed to decline rather than invent. Access is credit-metered: new accounts get 10 free interactions, and a credit is deducted only when a reply is successfully generated — failed requests cost nothing.
Chess AI (this site)
James built a fully playable chess game for this portfolio where the opponent runs entirely client-side — no server picks a move. The rules engine decides every legal move and the opponent only picks among those legal moves, which keeps legality separate from move choice. There are three heuristic difficulties (random, material-based, and a negamax search with alpha-beta pruning); the trained model is not in the browser yet, so the game honestly describes this as a heuristic stand-in. Beating the AI on any difficulty while signed in grants a one-time +5 JTB credit reward, verified by the server replaying the submitted moves to confirm the win.
Bank Customer Churn Prediction (R)
James compared churn-prediction models in R — logistic regression, SVM, random forest, and Naive Bayes — on a bank customer dataset, using exploratory analysis, feature engineering, and an 80/20 train/test split with four classifiers trained on the same partition. The random forest was selected as the best model, saved as a reusable artefact, and wrapped in a predict_churn() function so new customer records can be scored directly. The notebook is published on Kaggle.
Password Creator & Evaluator (Python)
James built a menu-driven password strength classifier on character-level TF-IDF plus engineered features, comparing tuned logistic regression, Naive Bayes, and SVM, with a companion tool that generates passwords. The notebook is published on Kaggle.
Where to see the projects
Every portfolio project listed above has a case-study page under the AI Projects section of this site (/ai-ml), and both JTB and the Chess AI are live — Chess at /chess, and JTB in this chat itself.

Languages & tools
Python and R for building and data work.
NumPy, Pandas, and PySpark for data manipulation and analysis.
Amazon Web Services (AWS) for cloud infrastructure, and GitHub Actions for automated pipelines.
Machine learning & AI
Machine Learning and Data Science, including data analysis and applied mathematics.
Generative AI and Agentic AI, including prompt engineering.
LangChain and LangGraph for LLM application and agent frameworks.
PydanticAI for AI application development.
Anthropic's Claude foundation models (through work on CBA's GenFolio, built on AWS, Vercel AI, and Claude).
DeepEval for LLM evaluation, and LLM-as-a-judge evaluation techniques.
HoneyHive for automated, self-improving evaluation pipelines.
Retrieval-Augmented Generation (RAG).
Certifications & coursework
Areas James has covered through completed certifications and structured courses (the full list is in the education section):
Claude ecosystem: Claude Code, Model Context Protocol (MCP), Claude Agent SDK, Anthropic API, Claude Skills, AI Subagents, and Claude Cowork.
Data fundamentals: Git and GitHub, SQL and PostgreSQL, Microsoft Excel (including pivot tables), and data analytics.
Web development: HTML, CSS, JavaScript and TypeScript, React, Django, and Flask.
Programming foundations: Python, R, with foundational coursework in Java and C#.
Software design: SOLID design principles and the architecture of modern large-scale systems.
Data science mathematics, machine learning, and natural language processing foundations.
`;
