#!/usr/bin/env python3
"""Regenerate the two bundled LLM Lab corpora (and print them for review).

    python training/llm/make_corpora.py

Outputs (both COMMITTED, marked generated — never hand-edit):

  lib/llm/bundledCorpus.ts   ~48 KB public-domain excerpt sliced from the
                             fetched Tiny Shakespeare (data/tinyshakespeare.txt;
                             run fetch_corpus.py first), extended to the next
                             paragraph boundary.
  lib/llm/portfolioCorpus.ts James's approved site copy: the live
                             content/jtb/*.md sections with markdown syntax
                             and [TODO placeholder lines stripped — the same
                             text JTB is grounded in. ~16 KB: a visitor's
                             model memorises rather than generalises, which is
                             the honest point of the "this site" corpus.

Both files embed a provenance header (sources, sha256, regeneration command).
"""

from __future__ import annotations

import hashlib
import re
from pathlib import Path

HERE = Path(__file__).resolve().parent
ROOT = HERE.parent.parent
SHAKESPEARE = HERE / "data" / "tinyshakespeare.txt"
KB_DIR = ROOT / "content" / "jtb"
OUT_BUNDLED = ROOT / "lib" / "llm" / "bundledCorpus.ts"
OUT_PORTFOLIO = ROOT / "lib" / "llm" / "portfolioCorpus.ts"

BUNDLED_TARGET_BYTES = 48 * 1024
KB_SECTIONS = ["about", "ai", "career", "education", "experience", "ml", "projects", "skills"]
TODO_MARKER = re.compile(r"^\s*\[TODO")


def sha256_short(data: bytes) -> str:
    return hashlib.sha256(data).hexdigest()[:16]


def ts_escape(text: str) -> str:
    """Escape for a TS template literal: backslashes first, then ` and ${."""
    return text.replace("\\", "\\\\").replace("`", "\\`").replace("${", "\\${")


def write_ts_module(path: Path, const_name: str, header: str, text: str) -> None:
    content = (
        f"/**\n{header}\n */\n\n"
        f"export const {const_name} = `{ts_escape(text)}`;\n"
    )
    path.write_text(content, encoding="utf-8")
    print(f"wrote {path.relative_to(ROOT)} ({len(text.encode('utf-8')):,} corpus bytes)")


# ---- bundled Shakespeare excerpt ---------------------------------------------


def bundled_excerpt() -> tuple[str, bytes]:
    raw = SHAKESPEARE.read_bytes()
    data = raw[: BUNDLED_TARGET_BYTES]
    # extend to the next blank-line boundary so the slice doesn't end mid-line
    tail = raw[BUNDLED_TARGET_BYTES : BUNDLED_TARGET_BYTES + 2048]
    boundary = tail.find(b"\n\n")
    if boundary != -1:
        data = raw[: BUNDLED_TARGET_BYTES + boundary + 2]
    return data.decode("utf-8"), raw


# ---- portfolio corpus ---------------------------------------------------------


def clean_markdown(md: str) -> str:
    lines: list[str] = []
    for line in md.splitlines():
        if TODO_MARKER.match(line):
            continue  # placeholder copy can never be trained on as fact
        text = line.strip()
        text = re.sub(r"^#{1,6}\s+", "", text)  # headings keep their words
        text = re.sub(r"^[-*]\s+", "", text)  # list markers
        text = re.sub(r"<!--.*?-->", "", text)
        if text:
            lines.append(text)
    return "\n".join(lines)


def portfolio_corpus() -> str:
    sections: list[str] = []
    for name in KB_SECTIONS:
        md = (KB_DIR / f"{name}.md").read_text(encoding="utf-8")
        cleaned = clean_markdown(md)
        if cleaned:
            sections.append(cleaned)
    return "\n\n".join(sections) + "\n"


def main() -> int:
    if not SHAKESPEARE.exists():
        raise SystemExit("missing data/tinyshakespeare.txt — run fetch_corpus.py first")

    excerpt, raw = bundled_excerpt()
    excerpt_bytes = excerpt.encode("utf-8")
    write_ts_module(
        OUT_BUNDLED,
        "BUNDLED_CORPUS",
        " * GENERATED by training/llm/make_corpora.py — do not hand-edit.\n"
        " * Bundled public-domain excerpt from Tiny Shakespeare\n"
        f" * (sha256 {sha256_short(raw)}..., bytes [0, {len(excerpt_bytes)}), extended to a\n"
        " * paragraph boundary). Source manifest: training/llm/corpus_sources.json.",
        excerpt,
    )

    portfolio = portfolio_corpus()
    write_ts_module(
        OUT_PORTFOLIO,
        "PORTFOLIO_CORPUS",
        " * GENERATED by training/llm/make_corpora.py — do not hand-edit.\n"
        " * James's approved site copy: content/jtb/{" + ", ".join(KB_SECTIONS) + "}.md\n"
        " * with markdown syntax and [TODO placeholder lines stripped (the same\n"
        " * text JTB is grounded in). Tiny by design — models memorise it.\n"
        f" * sha256 {sha256_short(portfolio.encode('utf-8'))}...",
        portfolio,
    )

    nbytes = len(portfolio.encode("utf-8"))
    print(f"portfolio corpus: {nbytes:,} bytes from {len(KB_SECTIONS)} KB sections")
    print("REVIEW: James should read lib/llm/portfolioCorpus.ts before training the sample.")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
